version: "3.6"
services:
  gekko:
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js
    links:
      - postgresql
    environment:
     - HOST
     - PORT
     - USE_SSL
     - VIRTUAL_HOST: www.qbittorrent.${LOCALDOMAIN}, qbittorrent.${LOCALDOMAIN} \
     - LETSENCRYPT_HOST: www.qbittorrent.${LOCALDOMAIN}, qbittorrent.${LOCALDOMAIN} \
     - LETSENCRYPT_EMAIL: tonibobone@gmail.com \
      # LETSENCRYPT_TEST: "true"
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}:${PORT}"
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko

postgresql:
  restart: on-failure:10
  image: postgres:9.6-alpine
  ports:
    - 5432:5432
  volumes:
    - ./_postgresql:/var/lib/postgresql/data:rw
  environment:
    - POSTGRES_DB: gekko
    - POSTGRES_USER: username
    - POSTGRES_PASSWORD: password

networks:
  default:
    external:
      name: webproxy
