version: "3.6"
services:
  gekko:
    build: ./
    volumes:
      #- ./volumes/gekko/history:/usr/src/app/history
      - ${GEKKO_FOLDER}/gekko/history:/home/gekko/app/history
      - ./config.js:/usr/src/app/config.js
    links:
      - postgresql
    environment:
    #  - HOST
    #  - PORT
      USE_SSL: ${USE_SSL}
      VIRTUAL_HOST: www.gekko.${LOCALDOMAIN}, gekko.${LOCALDOMAIN} \
      LETSENCRYPT_HOST: www.gekko.${LOCALDOMAIN}, gekko.${LOCALDOMAIN} \
      LETSENCRYPT_EMAIL: tonibobone@gmail.com \
      LETSENCRYPT_TEST: "true"
    # ports: # you can comment this out when using the nginx frontend
      # - "${PORT}:${PORT}"
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko

  postgresql:
    restart: on-failure:10
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ${DATAFOLDER}:/var/lib/postgresql/data:rw
      #- ./_postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  default:
    external:
      name: webproxy
